site_name: MiDB readthedocs

theme: material

plugins:
    - search
    
docs_dir: docs

pages: index.md
    - Studies and Groups
        - ABCD: StudiesGroups/ABCD.md
        - Sub-Populations in ADHD & ASD: StudiesGroups/ADHD_ASD.md
        - Infant Team: StudiesGroups/InfantTeam.md
        - NHP: StudiesGroups/NHP.md
        - Rodent Studies: StudiesGroups/Rodent.md
        - Movement Disorders: StudiesGroups/MovementDisorders.md
    - Accessing Servers
        - Computational Resources
            - Exacloud:
                - Registering for Access: AccessingServers/ComputationalResources/Exacloud/RegisteringAccess.md
                - Gaining Access: AccessingServers/ComputationalResources/Exacloud/GainingAccess.md
            - Rushmore:
                - Registering for Access: AccessingServers/ComputationalResources/Rushmore/RegisteringAccess.md
                - Gaining Access: AccessingServers/ComputationalResources/Rushmore/GainingAccess.md
            - MSI:
                - Registering for Access: AccessingServers/ComputationalResources/MSI/RegisteringAccess.md
                - Gaining Access: AccessingServers/ComputationalResources/MSI/GainingAccess.md
        - Data Transfers
            - DICOM Transfers
                - AIRC (OHSU): AccessingServers/DataTransfers/DICOMtransfers/AIRC.md
                - CMRR (UMN): AccessingServers/DataTransfers/DICOMtransfers/CMRR.md
            - Within Institution: AccessingServers/DataTransfers/WithinInstitution.md
            - Between Institutions: AccessingServers/DataTransfers/BetweenInstitutions.md

    - Contributors: contributors.md
