site_name: MIDB readthedocs

theme: material

plugins:
    - search
    
docs_dir: docs

nav: 
    - Welcome: index.md
    - Studies and Groups:
        - ABCD: studies/abcd.md
        - Sub-Populations in ADHD & ASD (UMN): studies/adhd_asd.md
        - ADHD & ASD (OHSU): 
        - Infant Team: studies/infant.md
        - Adult Team: studies/adult.md
        - NHP: studies/nhp.md
        - Rodent Studies: studies/rodent.md
        - Movement Disorders: studies/mvmt.md
    - Accessing Servers:
        - Computational Resources:
            - Exacloud:
                - Registering for Access: access/comp/exacloud/reg.md
                - Gaining Access: access/comp/exacloud/gain.md
            - Rushmore:
                - Registering for Access: access/comp/rushmore/reg.md
                - Gaining Access: access/comp/rushmore/gain.md
            - MSI:
                - Registering for Access: access/comp/msi/reg.md
                - Gaining Access: access/comp/msi/gain.md
        - Data Transfers:
            - DICOM Transfers:
                - AIRC (OHSU): access/data/dicom/airc.md
                - CMRR (UMN): access/data/dicom/cmrr.md
            - Within Institution: access/data/within.md
            - Between Institutions: access/data/between.md
    - Coding Standards:
        - Computing Environment Profile:
            - Exacloud: code/compute/exacloud.md
            - Rushmore: code/compute/rushmore.md
            - MSI: code/compute/msi.md
        - Folder Organizational Structure:
            - Software: code/folderorg/software.md
            - Projects: code/folderorg/projects.md
            - Imaging Data: code/folderorg/data.md
        - Permissions: code/permissions.md
        - Reporting Errors: code/errors.md
    - Programming Languages:
        - Bash: lang/bash.md
        - Python: lang/python.md
        - R: lang/r.md
        - Matlab: lang/matlab.md
    - Containers:
        - Docker: contain/docker.md
        - Singularity: contain/singularity.md
    - Pipeline Pre-Processing:
        - Locating DICOMs:
            - AIRC (OHSU): pipeline/locate/airc.md
            - CMRR (UMN): pipeline/locate/cmrr.md
        - Moving DICOMs to Server:
            - AIRC (OHSU): pipeline/move/airc.md
            - MSI (UMN): pipeline/move/msi.md
        - DICOMs to NIFTIs: pipeline/dn.md
        - QC-ing NIFTIs: pipeline/qc.md
        - Respiration Rate Settings: pipeline/respir.md
    - Manual Processing via DCAN Pipelines:
        - ABCD: manualpro/abcd.md
        - Infant Team: manualpro/infant.md
        - NHP: manualpro/nhp.md
        - Rodent: manualpro/rodent.md
    - Cleaning Intermediate Files:
        - Custom Clean: clean/custom.md
        - Filemapper: clean/filemap.md
    - DCAN Processing Tools:
        - BIDS GUI: protool/bids.md
        - DADS App: protool/dads.md
    - Neuroimaging Software:
        - FreeSurfer: software/freesurfer.md
        - Freeview: software/freeview.md
        - FSL: software/fsl.md
        - Workbench: software/workbench.md
        - SPM: software/spm.md
    - DCAN Analysis Tools:
        - Seed Map Parcellation Wrapper:
            - Overview: analysis/seed/intro.md
            - Code and SOP: analysis/seed/code.md
            - Video Walkthrough: analysis/seed/video.md
            - Release History: analysis/seed/release.md
        - PALM: 
            - Overview: analysis/palm/intro.md
            - Code and SOP: analysis/palm/code.md
            - Video Walkthrough: analysis/palm/video.md
            - Release History: analysis/palm/release.md
        - Template Matching: 
            - Overview: analysis/temp/intro.md
            - Code and SOP: analysis/temp/code.md
            - Video Walkthrough: analysis/temp/video.md
            - Release History: analysis/temp/release.md
        - Random Forest: 
            - Overview: analysis/forest/intro.md
            - Code and SOP: analysis/forest/code.md
            - Video Walkthrough: analysis/forest/video.md
            - Release History: analysis/forest/release.md
        - F Conn Regression: 
            - Overview: analysis/fconn/intro.md
            - Code and SOP: analysis/fconn/code.md
            - Video Walkthrough: analysis/fconn/video.md
            - Release History: analysis/fconn/release.md
        - Cifti Conn Matrix:
            - Overview: analysis/cifti/intro.md
            - Code and SOP: analysis/cifti/code.md
            - Video Walkthrough: analysis/cifti/video.md
            - Release History: analysis/cifti/release.md
        - Community Detection:
            - Overview: analysis/comm/intro.md
            - Code and SOP: analysis/comm/code.md
            - Video Walkthrough: analysis/comm/video.md
            - Release History: analysis/comm/release.md
        - Marginal Model CIFTI:
            - Overview: analysis/marg/intro.md
            - Code and SOP: analysis/marg/code.md
            - Video Walkthrough: analysis/marg/video.md
            - Release History: analysis/marg/release.md
        - Automated Subset Analysis:
            - Overview: analysis/auto/intro.md
            - Code and SOP: analysis/auto/code.md
            - Video Walkthrough: analysis/auto/video.md
            - Release History: analysis/auto/release.md
        - BWAS:
            - Overview: analysis/bwas/intro.md
            - Code and SOP: analysis/bwas/code.md
            - Video Walkthrough: analysis/bwas/video.md
            - Release History: analysis/bwas/release.md
        - Poly Conn:
            - Overview: analysis/poly/intro.md
            - Code and SOP: analysis/poly/code.md
            - Video Walkthrough: analysis/poly/video.md
            - Release History: analysis/poly/release.md
    - DCAN Visualization Tools:
        - Figure Maker:
            - Code and SOP: visual/figure/code.md
            - Video Walkthrough: visual/figure/video.md
            - Release History: visual/figure/release.md
        - ShowM:
            - Code and SOP: visual/show/code.md
            - Video Walkthrough: visual/show/video.md
            - Release History: visual/show/release.md
        - Plot Histogram:
            - Code and SOP: visual/plot/code.md
            - Video Walkthrough: visual/plot/video.md
            - Release History: visual/plot/release.md
        - Skinny Plot:
            - Code and SOP: visual/skin/code.md
            - Video Walkthrough: visual/skin/video.md
            - Release History: visual/skin/release.md
    - Utility Tools:
        - Downloading from NDA: utility/nda.md
        - Filemapper: utility/filemap.md
        - GUI Environment: utility/gui.md
        - Reference Bias Checker: utility/bias.md
    - Linux:
    - Contributors: contributors.md
